# Problem 2 : Statement:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose
# values do not exceed four million,
# find the sum of the even-valued terms.


def main():

    sum = 0
    series = [1, 2, 3]   # append each new variable
    i = 2
    while series[i] <= 4000000:
        series.append(series[i] + series[i-1])
        i = i + 1

    for j in range(len(series)):
        if series[j] % 2 == 0:
            sum = series[j] + sum
        else:
            pass
    print(sum)


if __name__ == '__main__':
    main()